import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1440,height:900}, deviceScaleFactor:1, reducedMotion:'reduce' });
await ctx.addInitScript(() => { try { localStorage.setItem('backroom-cookie-notice','ok'); } catch {} });
const p = await ctx.newPage();
await p.goto('http://localhost:4367/ueber-uns', { waitUntil:'networkidle', timeout:45000 });
await p.evaluate(async()=>{await new Promise(r=>{let y=0,h=document.body.scrollHeight;const s=()=>{y+=500;scrollTo(0,y);y<h?setTimeout(s,35):(scrollTo(0,0),setTimeout(r,300))};s();});});
await p.waitForTimeout(400);
await p.screenshot({ path:'docs/qa/ueber-uns-d.jpg', fullPage:true, quality:75, type:'jpeg' });
await b.close(); console.log('shot done');
